Fixed company logo not loading on non-root-path installations
FOSSBilling/FOSSBilling pull request #111
Opened 2022-05-30 00:46 UTC by Komodroid

There was a little issue when running relative path installs which was about the default software & company branding, caused by the use of an absolute path by default.
This should be fixed now in this PR.
Small contribution 😃.

2022-05-30 03:06 UTC, BelleNottelling approved these changes

2022-05-30 08:52 UTC, andpavlenko commented
Please setup your IDE to use PHP CS Fixer with config in project root dir.

2022-05-30 08:55 UTC, jaapmarcus reviewed
Not related to the PR it self but we should fix it anyway

2022-05-30 08:55 UTC, jaapmarcus commented on src/bb-modules/System/Service.php
>                  WHERE param IN('".implode("', '", $params)."')
Contains vulnrebility for a potential sql injection we need to filter those values before use in a query

2022-05-30 22:46 UTC, Komodroid commented
Don't know why it is failing X_X can anyone check please? (Works fine on my end)

2022-05-31 06:13 UTC, jaapmarcus requested changes

2022-05-31 21:38 UTC, jaapmarcus approved these changes

2022-06-01 17:50 UTC, merged