Minor changes to the extension directory templates
FOSSBilling/FOSSBilling pull request #1130
Opened 2023-04-20 18:31 UTC by evrifaessa

2023-04-21 13:15 UTC, admdly requested changes
Just one test needs updating so that it passes, but otherwise LGTM. 🙂

2023-04-21 13:15 UTC, admdly commented on src/modules/Extension/Service.php
> +            throw new \Box_Exception('Visit the extension directory for more information on updating this extension.', null, 252);
The `testupdate` function in `Box\Mod\Extension\ServiceTest` needs to be updated with the new exception wording the fix the test error: 

>>> Failed asserting that exception message 'Visit the extension directory for more information on updating this extension.' contains 'Visit the extension store for more information on updating this extension.'.

2023-04-22 07:18 UTC, BelleNottelling approved these changes

2023-04-22 07:55 UTC, jaapmarcus approved these changes

2023-04-22 11:24 UTC, admdly approved these changes

2023-04-22 11:24 UTC, merged