Renamed phonestate_cc to city in admin/client/update
FOSSBilling/FOSSBilling pull request #1352
Opened 2023-06-20 12:23 UTC by avaneeshk098

In the admin/client/update function, when a user requests to update the city for a desired client. 
They have to use the pair as `{"phonestate_cc": "<city_name>"}` instead of `{"city": "<city_name>"}`. 

This issue caused a lot of confusion since the docs mention to update the city for a client, we must use the key: **city**. However, this query won't work since the actual key in the code is **phonestate_cc**. 

I have updated one code line to fix this minor issue.

2023-06-20 12:32 UTC, BelleNottelling requested changes
The front-end must also be updated to use this key

2023-06-20 12:46 UTC, avaneeshk098 commented
> The front-end must also be updated to use this key

Can you guide me about which files in the front end utilise this key?

2023-06-20 13:16 UTC, BelleNottelling commented
> > The front-end must also be updated to use this key
> 
> Can you guide me about which files in the front end utilise this key?

Huh. I can't actually find anywhere in the front-end where it's not named "city".
Well, then I'm quite confused where the usage of `phonestate_cc` came from, but it looks like this issue would effect both API users and the front-end.

So thanks for the patch :)

2023-06-20 13:16 UTC, BelleNottelling approved these changes

2023-06-21 05:30 UTC, jaapmarcus approved these changes

2023-06-21 17:55 UTC, merged

2023-06-21 17:55 UTC, BelleNottelling commented
Thanks :)