Hide version and company info from guests
FOSSBilling/FOSSBilling pull request #1504
Opened 2023-07-31 13:08 UTC by Anuril

Discord-User Pielgrzym mentioned that he'd like to hide the version number from the public. 

I also found that the api/guest/system/company endpoint returned the company data. 

AFAIK only the version endpoint is used in the admin area. The company endpoint isn't - and to be honest, I also like the idea of being able to disable this. 

I've added the settings to Admin -> Company, and added checks to getVersion & getCompany. 

Version now checks if the request comes from a logged in Admin, and returns the version (no matter the setting). 
After that, both functions check for the setting in the database.

2023-07-31 17:39 UTC, jaapmarcus approved these changes

2023-07-31 17:42 UTC, BelleNottelling requested changes
This simply just won't work. Lots of portions of the front-end use the `company` API endpoint and will be adversely effected by removing or disabling that endpoint. https://github.com/search?q=repo%3AFOSSBilling%2FFOSSBilling%20guest.system_&type=code

2023-07-31 17:42 UTC, BelleNottelling commented on src/modules/System/Api/Guest.php
> +        if ($showVersionPublic == 1) {
Don't need to check and verify if it's set to 1.
`if($showVersionPublic)` will evaluate to true if the value is set and non-falsey. Meaning if it's set and is equal to 1, the check will pass. 

If it's not set or it's set to 0, the check will not pass.

2023-07-31 17:42 UTC, BelleNottelling commented on src/modules/System/Api/Guest.php
> +        if ($showCompanyPublic == 1) {
Same thing here

2023-07-31 19:05 UTC, Anuril commented
You're right... I missed that somehow :O 

I still don't like having my VAT, Bank Account, Phone number and E-Mail publicly accessible via an API. 

I want to rework this but I'll do it at a later stage. 

Sorry for wasting your time :/

2023-07-31 19:47 UTC, BelleNottelling commented
> You're right... I missed that somehow :O
> 
> I still don't like having my VAT, Bank Account, Phone number and E-Mail publicly accessible via an API.
> 
> I want to rework this but I'll do it at a later stage.
> 
> Sorry for wasting your time :/

My suggestion is to just `unset` the array keys you want to keep a little more private if the API request is being made by someone who's not authenticated.

```PHP
public function company()
{
    $companyInfo = $this->getService()->getCompany();
    $auth = $this->di['auth'];
    $showCompanyPublic = $this->getService()->getParamValue('show_company_public');
    
    if(!$auth->isAdminLoggedIn() && !$auth->isClientLoggedIn() && !$showCompanyPublic){
        unset($companyInfo['vat_number']);
        unset($companyInfo['email']);
        unset($companyInfo['tel']);
        unset($companyInfo['account_number']);
        unset($companyInfo['number']);
    
        unset($companyInfo['address_1']);
        unset($companyInfo['address_2']);
        unset($companyInfo['address_3']);
    }
    
    return $companyInfo;
}
```

2023-08-02 17:27 UTC, BelleNottelling approved these changes
I've made some changes and this PR is now to a point where I'm personally happy with it

2023-08-02 17:40 UTC, jaapmarcus approved these changes

2023-08-02 17:40 UTC, merged