Removed passwords from event data
FOSSBilling/FOSSBilling pull request #1721
Opened 2023-10-13 10:10 UTC by Anuril

I've noticed that on several locations, user and admin-provided passwords were passed to events. 
Because events can be hooked from any extension, this would allow any extension to get passwords in cleartext when they get changed. 
IMO, we should do as few things as possible with cleartext password data, this is why I've removed it from where I found. I've only found one location where any of the events were used: onBeforeClientSignup is used in the Spamchecker module, but that doesn't do anything with the password, so there should be no impact at all.

2023-10-14 00:25 UTC, BelleNottelling requested changes
See the comment.

I am also labeling this as a breaking change because it's exactly that.
There are legitimate use-cases where someone may need event-based access to this info (the most clear one is automated syncing between FOSSBilling and another platform, potentially even some kind of in-house tool.)

And while I understand the potential concerns for making that available in an event, it's pretty trivial for malicious code that to collect this information anyways and in just a handful of lines of PHP code they can just modify a function within another module to the add this info into the hook params once again, or even fire off a custom event that's specifically for their malicious intentions.
There is minimal we can do about an end-user installing malicious code and allowing it to be executed which is part of why it's important that we get the Extension Directory to a more functional state. That gives us a platform to do checks and balances against code and if someone exclusively installs extensions through there then their chances of getting something malicious would be significant lower VS finding something randomly shared online and plopping it into their installation.

Because of this, I am also going to block this from being merged until other team members share their thoughts.

I think it's important we find the right balance between blocking legitimately useful features in hopes of adding additional layers of security that can very easily be worked around and accepting that we can't prevent every edge-case and sometimes it might be better to retain the valuable functionality for the legitimate use-cases that do exist.

2023-10-14 00:25 UTC, BelleNottelling commented on src/modules/Client/Api/Admin.php
> +        $eventDataBefore = $data;
The `update` function doesn't do anything with passwords, this additional logic doesn't need to be here.

2023-10-14 01:55 UTC, Anuril commented
You're right, the security benefit isn't very large, and malicious code could get that information pretty easily. I also think that re-using passwords from fossbilling for other systems is not per se a good idea / solution, as there are other solutions for SSO.

I can also see the many other things with higher priority we need to do before that... I honestly don't feel too strongly about this and the change wasn't a lot of work.

2023-10-14 20:05 UTC, closed without merging

2023-10-16 09:44 UTC, admdly commented
Agree with @BelleNottelling. 

Longer term, once the extension directory is fully operational, it may be an idea to implement some form of valid signature checking before permitting an extension access to sensitive data.