Redirect admin to previous url after login
FOSSBilling/FOSSBilling pull request #1745
Opened 2023-10-21 10:27 UTC by jelmer-visser

This pull request introduces a new feature aimed at improving the user experience during the authentication flow. 

If an unauthenticated administrator attempts to access a route that requires authentication, they will be redirected to the login page. A redirect parameter, capturing the initially requested route, is appended to the login page URL. 

Upon successful login, the administrator is automatically redirected back to the page they were initially trying to access, ensuring a seamless navigation experience. This enhancement not only streamlines the navigation process but also retains the user's intended navigation path post-authentication.

2023-10-21 16:20 UTC, BelleNottelling requested changes
Great start, but it's probably ~40% of what's needed to close out the linked issue:
 1) Ideally this would be implemented for both the admin panel as well as the client area. Honestly it's more important for the client area from a usability perspective.
 2) I don't like the idea of the return URL being sent via GET parameters as that opens this up to [unvalidated redirects & forwards](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html).

2023-10-21 16:25 UTC, jelmer-visser commented
What would you suggest? Storing the uri in the session? I will add support
for the client :-)

Op za 21 okt. 2023 18:20 schreef Belle Aerni ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Great start, but it's probably ~40% of what's needed to close out the
> linked issue:
>
>    1. Ideally this would be implemented for both the admin panel as well
>    as the client area. Honestly it's more important for the client area from a
>    usability perspective.
>    2. I don't like the idea of the return URL being sent via GET
>    parameters as that opens this up to unvalidated redirects & forwards
>    <https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html>
>    .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FOSSBilling/FOSSBilling/pull/1745#pullrequestreview-1691285823>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR7SW32WRUWA4YDHCLUSDQ3YAPY4RAVCNFSM6AAAAAA6KBUKOGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOJRGI4DKOBSGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-21 16:49 UTC, BelleNottelling commented
> Storing the uri in the session?

Yeah, I think that sounds like a good option :)

2023-10-26 02:41 UTC, BelleNottelling reviewed
Looks better, just two minor things and I'm happy.
Thanks!

2023-10-26 02:41 UTC, BelleNottelling commented on src/di.php
> +    $redirectUri = str_replace('/admin', '', $url) . '?' . http_build_query($_GET);
The admin area prefix can be changed, so we can't hard-code it to `/admin`, instead you should use the `ADMIN_PREFIX` constant

2023-10-26 02:41 UTC, BelleNottelling commented on src/di.php
> +$di['set_redirect_uri'] = function () use ($di) {
It's pretty nitpicky, I know, but I think that `set_return_uri` better fits the actual usecase of this function

2023-10-26 22:07 UTC, BelleNottelling approved these changes
I pushed a small commit to use the `ADMIN_PREFIX` constant rather than directly referencing the config file. LGTM now

2023-10-26 22:21 UTC, jaapmarcus approved these changes

2023-10-26 22:25 UTC, jelmer-visser commented
> I pushed a small commit to use the `ADMIN_PREFIX` constant rather than directly referencing the config file. LGTM now

Yeah I saw it like this somewhere in de codebase that's why I did it like this. But good to know :-)

2023-10-26 22:34 UTC, BelleNottelling commented
> Yeah I saw it like this somewhere in de codebase that's why I did it like this. But good to know :-)

I'm not surprised, that definitely happens. I've made an issue to go and update these where applicable to use constants rather than direct references for improved maintainability. Thanks for pointing that out

2023-10-27 18:16 UTC, John-S4 approved these changes

2023-10-27 18:17 UTC, merged