Updated some logos and favicons
FOSSBilling/FOSSBilling pull request #184
Opened 2022-07-22 20:48 UTC by evrifaessa

2022-07-23 05:36 UTC, John-S4 commented
Why are you using such strange background sizing instead of whole pixel values?

`background-size: 117.12px 138.24px;`

2022-07-23 05:46 UTC, jaapmarcus commented
Also prefer if .svg is used instead of .png as it scales better

2022-07-23 06:00 UTC, John-S4 commented
> Also prefer if .svg is used instead of .png as it scales better

Agreed

2022-07-23 06:42 UTC, jaapmarcus requested changes
It also makes sense to have a "dark mode" version available in the repo when needed.

2022-07-23 06:42 UTC, jaapmarcus commented on src/bb-load.php
> +              background-image: url('/bb-themes/boxbilling/assets/images/fb_wallet.png');
Why .png and not .svg?

2022-07-23 06:42 UTC, jaapmarcus commented on src/bb-load.php
> +              background-size: 117.12px 138.24px;
Why not rounded numbers? Doesn't it create any strange artifacts?

2022-07-23 13:20 UTC, evrifaessa commented
> Why are you using such strange background sizing instead of whole pixel values?
> 
> `background-size: 117.12px 138.24px;`

It's the 40% of the original size. I'll get the circle bigger and make the logo 50% to make the numbers integers.

2022-07-23 13:26 UTC, evrifaessa commented
> It also makes sense to have a "dark mode" version available in the repo when needed.

Two versions of the wordmark exist both in the branding repo and the theme assets.

![image](https://user-images.githubusercontent.com/35808275/180607000-1eeddead-1470-4598-83e5-743768f56098.png)

2022-07-23 13:38 UTC, evrifaessa commented
Also uploaded the svg versions and used them wherever I can.

2022-07-23 13:38 UTC, evrifaessa commented
One thing left is this grayscale BoxBilling logo in the footer of the boxbilling theme.
I don't know what to replace this with.

![image](https://user-images.githubusercontent.com/35808275/180607484-dea8449e-dfda-4f00-aa35-4a82ffa9e88b.png)

2022-07-23 13:42 UTC, evrifaessa commented
Another thing is this icon that comes from the branding module

![image](https://user-images.githubusercontent.com/35808275/180607622-faf6f134-58bb-4b6d-b97a-bcd1dbc10073.png)

2022-07-23 13:43 UTC, jaapmarcus approved these changes

2022-07-24 17:32 UTC, John-S4 commented
> One thing left is this grayscale BoxBilling logo in the footer of the boxbilling theme. I don't know what to replace this with.
> 
> ![image](https://user-images.githubusercontent.com/35808275/180607484-dea8449e-dfda-4f00-aa35-4a82ffa9e88b.png)

I'd be tempted to use the logo with black text, and apply a CSS greyscale filter.

2022-07-25 23:59 UTC, chippytech commented
What about this
![download (3)](https://user-images.githubusercontent.com/80016011/180894494-8568a64a-79bd-4752-8279-eeca50b58d20.png)

2022-07-26 12:32 UTC, John-S4 commented
Just use one of the existing files and apply a grayscale filter if it needs to be without colour, otheriwse just use the logo with colour in the footer, then let's get it merged and rid of that old bb logo popping up everywhere.

2022-07-26 12:33 UTC, John-S4 approved these changes
All looks good, just do something with that footer logo and then merge it.

2022-07-26 12:53 UTC, evrifaessa commented
With a full grayscale effect and 50% opacity, the footer logo looks like this:

![image](https://user-images.githubusercontent.com/35808275/181010474-e647d15f-8bc9-47ff-9ed1-258b9628738e.png)

2022-07-26 13:00 UTC, merged