✨Add prefix for generated users (continuation)
FOSSBilling/FOSSBilling pull request #2101
Opened 2024-01-27 22:21 UTC by guillaumearnx

Good evening,

as mentioned in the PR #1378, it would be interesting to have the possibility of generating a prefix for the users created on the different managers.

I see that in some managers, the method is overridden.
I therefore still wanted to include this option.
Ignored option for CPanel due to restrictions (max 16 characters). This is specified on the front and translated into a few languages.

Thank you so much

2024-01-27 23:21 UTC, jaapmarcus requested changes
Please remove the changes as there is allready a PR for it

2024-01-27 23:38 UTC, guillaumearnx commented
Sorry thats a bug unwanted frome me. Have a good day

2024-01-28 20:59 UTC, BelleNottelling reviewed
The functional changes look good, I'd just prefer different wording for the configure page

2024-01-28 20:59 UTC, BelleNottelling commented on src/modules/Servicehosting/html_admin/mod_servicehosting_server.html.twig
> +                    <input class="form-control" type="text" name="userprefix" value="{{ server.config.userprefix }}" placeholder="{{ 'Prefix for created users (especially for database) | Ignored for
I'd probably add a `span` under this input with the `text-muted` class and write out something similar to "Some server managers may ignore this option due to limitations / requirements for usernames imposed by the control panel".

That way we don't need to remember to change this if any others end up not using the prefix & we are less likely to have people submitting a bug report if their 3rd party server manager doesn't use it

2024-01-30 19:00 UTC, guillaumearnx commented
indeed, this is preferable. thanks for the advice

2024-01-30 23:40 UTC, BelleNottelling commented on src/modules/Servicehosting/html_admin/mod_servicehosting_server.html.twig
> +                    <span class="text-muted">{{ 'Some server managers may ignore this option due to limitations / requirements for username imposed by the control panel.'|trans }}</span>
Typo, I think "username" was supposed to be "usernames"

2024-01-30 23:41 UTC, guillaumearnx commented
very likely not being an expert in English

2024-01-31 00:32 UTC, BelleNottelling approved these changes
Cheers, thanks for the PRs!

2024-01-31 06:03 UTC, jaapmarcus approved these changes

2024-01-31 08:15 UTC, merged