Update mod_client_profile.html.twig
FOSSBilling/FOSSBilling pull request #2517
Opened 2024-11-28 13:36 UTC by 1a-websolutions

correctly Phone_cc view for the Clients detailpage

2024-12-18 00:11 UTC, admdly commented
I'm not sure if the `+` should be included directly in the field, or as a displayed character only as in the admin area. However, as it stands, it is an improvement to the client area so I'll approve this pending review from other reviewers.

Going forward it would also be more helpful to describe your proposed changes in PRs if you'd like them to be considered.

2024-12-18 00:11 UTC, admdly approved these changes
Improvement, but should perhaps be display only rather than modifying the field value?

2024-12-27 20:55 UTC, BelleNottelling requested changes
If someone isn't paying attention to this on their profile (which they shouldn't need to), it'll either:

A) Produce an error when they try to save changes to their profile because the system isn't expecting a plus in the field.

or

B) If the system does allow the plus to be there, this change will cause a new plus to be added every time they save changes in their profile.

EX:
Their country code is `1` for the US. This change appends `+` to the front of it within the field value. They change something other than their country code and hit save. That plus is now saved as part of their country code, making it `+1`.
Then, they go back at a later date to make a different change. That `+1` gets another plus added to the front of it, making the value in the input `++1`. They save their other, unrelated change, and then now `++1` is the value being sent to the back end.I don't believe that it'll allow that to be saved, but even then it'll produce an error

2025-03-06 00:37 UTC, admdly commented
@1a-websolutions thank you for this contribution, as with you other contribution -  it is very much appreciated. Unfortunately, unless you address the detailed feedback provided by @BelleNottelling, we will have to close this pull request.

2025-03-10 18:45 UTC, admdly commented
Unfortunately, this PR seems abandoned with outstanding issues - closing.

2025-03-10 18:45 UTC, closed without merging