BugFix Issue #262 Prevent cron from paying deposit invoice with credits
FOSSBilling/FOSSBilling pull request #265
Opened 2022-09-15 16:37 UTC by DataLores

Deposit invoices types are generated during client add funds and should only be payable via payment gateways with valid transactions.

2022-09-16 09:50 UTC, jaapmarcus requested changes

2022-09-16 09:50 UTC, jaapmarcus commented on src/bb-modules/Invoice/ServiceInvoiceItem.php
> -            $invoice = $this->di['db']->getExistingModelById('Invoice', $item->invoice_id);
Due to changes here the test seems to be failing

1) Box\Mod\Invoice\ServiceInvoiceItemTest::testexecuteTaskTypeDeposit
[44](https://github.com/FOSSBilling/FOSSBilling/actions/runs/3062942591/jobs/4949750766#step:10:45)
Expectation failed for method name is "getExistingModelById" when invoked at least once.
[45](https://github.com/FOSSBilling/FOSSBilling/actions/runs/3062942591/jobs/4949750766#step:10:46)
Expected invocation at least once but it never occurred.

It seems this function is used for automated testing to add "deposit" to the user

2022-09-16 09:50 UTC, jaapmarcus commented on src/bb-modules/Invoice/ServiceInvoiceItem.php
> -            $invoice = $this->di['db']->getExistingModelById('Invoice', $item->invoice_id);
Or we need to update ...

2022-09-25 09:10 UTC, evrifaessa approved these changes
LGTM. Was able to reproduce the problem and confirm the fix.

2022-09-25 09:12 UTC, jaapmarcus approved these changes

2022-09-25 09:12 UTC, merged

2022-09-25 09:12 UTC, jaapmarcus commented
👍🏼  Thanks