Blocked access to Twig template files in Apache and Lighttpd conf
FOSSBilling/FOSSBilling pull request #394
Opened 2022-10-27 20:03 UTC by evrifaessa

We've migrated from .phtml to .html.twig long ago. This PR updates the server configuration files to block direct access to Twig template files with the new extension.

2022-10-27 20:09 UTC, jaapmarcus requested changes
Also update nginx template

2022-10-27 20:12 UTC, BelleNottelling approved these changes

2022-10-28 09:38 UTC, evrifaessa commented
@jaapmarcus done. Also updated all of them to return 404 instead of 403.

2022-10-28 15:03 UTC, jaapmarcus requested changes

2022-10-28 15:03 UTC, jaapmarcus commented on data/nginx.conf
> +     location ~ (\.htaccess$|\.htpasswd$|\.ini$|\.log$|\.sh$|\.inc$|\.bak$|\.twig$|\.sql$) {
.htaccess and .htpassword is allready blocked by 
https://github.com/FOSSBilling/FOSSBilling/blob/e0cb529ca86351cfa80e1a34a563853d81a092eb/data/nginx.conf#L56-L58

How ever I suggest blocking  all hidden files by:

https://github.com/hestiacp/hestiacp/blob/e3e172d893f20c303941a1ab2d846eeb823a9179/install/deb/templates/web/nginx/php-fpm/default.tpl#L42-L45

Also this looks nicer:
 location ~* ^.+\.(ini|sh|inc|bak|twig|sql|)$ {

2022-10-29 13:54 UTC, evrifaessa commented
@jaapmarcus I've changed the files according to your suggestions. Anything else?

2022-10-29 14:00 UTC, jaapmarcus approved these changes

2022-10-29 14:00 UTC, jaapmarcus commented
No

2022-10-29 14:02 UTC, merged