Created a CSRF token system
FOSSBilling/FOSSBilling pull request #526
Opened 2022-12-04 03:53 UTC by BelleNottelling

This PR protects the API through a CSRF token. The only times the token isn't needed is if there isn't a valid PHP session, for guest accounts, or if the API is being calling through CLI. 
This is a majorly breaking change, but it's needed to protect FOSSBilling from CSRF vulnerabilities.

I'm not sure if there's a better way to do it, but I created a new twig extension to add a hidden input element with the token.

Please review and test, we will also need to make a note of this on our docs for developers.

2022-12-04 04:47 UTC, jaapmarcus reviewed
It also need to be added to all get requests that can do actions like deleting certain things

2022-12-04 04:59 UTC, BelleNottelling commented
> It also need to be added to all get requests that can do actions like deleting certain things

Ah yeah.. I guess I have more work to do then lol

2022-12-04 05:09 UTC, jaapmarcus commented
Yes, But it is already a great start!

2022-12-05 07:38 UTC, BelleNottelling commented
Okay, I believe this PR is ready for testing & reviews.
I've verified on my end that the API still works as expected when the token is provided, if it isn't you get an "authentication failed" error.

Disabling the protection also works as intended so that exists for backwards compatibility (tho nobody should ever disable it)
I've updated all forms in the software and any links that performed API requests to have the token, which is stored as a global variable inside of twig and can be accessed via ``{{ CSRFToken }}``

2022-12-05 14:14 UTC, jaapmarcus requested changes
Haven't check everything else yet but the installer doesn't check it either...

2022-12-05 19:01 UTC, BelleNottelling commented on src/install/assets/install.html.twig
> +            <input type="hidden" name="CSRFToken" value="{{ CSRFToken }}"/>
Should be fixed now

2022-12-05 19:26 UTC, jaapmarcus requested changes

2022-12-05 22:11 UTC, jaapmarcus reviewed
I can't find the "exact" location but when a POST request is made via jQuery and an error is generated no feed back is present. 
<img width="489" alt="Screenshot 2022-12-05 at 22 48 11" src="https://user-images.githubusercontent.com/9754650/205753127-b7b5cdfe-b3f1-4145-827d-567643cca104.png">

Ideally we should "show" an error. 

This was the case with "Add new user"

2022-12-06 17:47 UTC, jaapmarcus approved these changes

2022-12-06 17:47 UTC, merged