Create an alias for bb-ipn
FOSSBilling/FOSSBilling pull request #605
Opened 2022-12-17 19:16 UTC by BelleNottelling

This PR adds an alias to our example configs from `bb-ipn.php` to `ipn.php` which is needed for those who have upgraded from BoxBilling

2022-12-17 19:25 UTC, evrifaessa approved these changes

2022-12-18 06:52 UTC, jaapmarcus requested changes
I don't know why but 

```
 location /bb-ipn.php {
             alias /ipn.php;
         }
```

Doesn't seem to be working on Nginx

2022-12-18 19:29 UTC, BelleNottelling commented
> I don't know why but
> 
> ```
>  location /bb-ipn.php {
>              alias /ipn.php;
>          }
> ```
> 
> Doesn't seem to be working on Nginx

Did you restart nginx?
The code is correct based on everything I am seeing online

2022-12-18 19:41 UTC, jaapmarcus commented
> > I don't know why but
> > ```
> >  location /bb-ipn.php {
> >              alias /ipn.php;
> >          }
> > ```
> > Doesn't seem to be working on Nginx
> 
> Did you restart nginx? The code is correct based on everything I am seeing online

Yes off course I did...

2022-12-18 19:49 UTC, BelleNottelling commented
> 

Hmm. Can you try this instead?

```
    location /bb-ipn.php {
        try_files $uri $uri/ ipn.php;
    }
```

2022-12-18 20:35 UTC, jaapmarcus commented
> Hmm. Can you try this instead?
> 
> ```
>     location /bb-ipn.php {
>         try_files $uri $uri/ ipn.php;
>     }
> ```

Nope the easiest way if you have old / existing bb-ipn.php users is create the file and include ipn.php

2022-12-18 22:49 UTC, John-S4 commented
Why is there a `./` in the lighttpd one, has the directory changed?

 `"/bb-ipn.php" => "./ipn.php"`

2022-12-18 23:28 UTC, BelleNottelling commented
> Why is there a `./` in the lighttpd one, has the directory changed?
> 
> `"/bb-ipn.php" => "./ipn.php"`

Fixed this

2022-12-18 23:30 UTC, BelleNottelling commented
Okay, so I just pushed a new update which will remove the check for bb-ipn.php.
This will allow people to create a file under that name which includes the new ipn.php file.

I think we should merge this PR and then update the migration docs to include the steps for creating the bb-ipn.php file

2022-12-19 09:18 UTC, jaapmarcus commented
If we allow bb-ipn.php to be created we should update the nginx conf files

2022-12-19 09:19 UTC, jaapmarcus requested changes

2022-12-19 09:19 UTC, jaapmarcus commented on data/docker-nginx.conf
> +        location /bb-ipn.php {
Can be removed

2022-12-19 09:19 UTC, jaapmarcus commented on data/nginx.conf
> +    location /bb-ipn.php {
Same here

2022-12-19 18:49 UTC, jaapmarcus approved these changes

2022-12-19 20:05 UTC, merged