Add requirement check for xml
FOSSBilling/FOSSBilling pull request #639
Opened 2022-12-29 20:07 UTC by jaapmarcus

2022-12-29 20:11 UTC, BelleNottelling requested changes
We should also update our readme (and the note about PHP 8.2, since it's been released)

2022-12-30 09:13 UTC, jaapmarcus commented
> We should also update our readme (and the note about PHP 8.2, since it's been released)

Done

2022-12-30 11:03 UTC, John-S4 approved these changes

2022-12-30 18:08 UTC, BelleNottelling approved these changes

2022-12-30 18:08 UTC, merged