Fix issue #665
FOSSBilling/FOSSBilling pull request #668
Opened 2023-01-05 22:27 UTC by BelleNottelling

This PR closes #665 by updating the `reformatJSON` function to specifically handle special cases where the variable is named like `upgrades[]`.

Instead of the normal behavior, it'll instead remove the brackets from the name and convert the value to an array.

I also fixed a dumb typo

2023-01-05 22:48 UTC, jaapmarcus requested changes
It doesn't seem to solve the issue with multi selects and selecting multiple options at same time. It works fine you only select one.

2023-01-10 09:16 UTC, BelleNottelling commented
> It doesn't seem to solve the issue with multi selects and selecting multiple options at same time. It works fine you only select one.

Yeah, turns out the issue is with the multi-select specifically and the root issue is further up. Updated the title to better reflect what this PR does fix

2023-01-10 09:28 UTC, jaapmarcus commented
With multiple imputs formatted as

<input type="checkbox" value="1" name="name[]"> Option 1
<input type="checkbox" value="2" name="name[]"> Option 2

Has the same "Problem" so far I can see the issue is not in the api wrapper but in 

https://github.com/FOSSBilling/FOSSBilling/blob/042e056b8edebedfdd47e58aad9b6b5da988e8fb/src/themes/admin_default/assets/js/fossbilling.js#L122-L145

as the input the Api wrapper receives is allready messed up.

2023-01-10 10:30 UTC, jaapmarcus commented
And it seems I am right:
https://jsfiddle.net/vzapndcL/

Compare the post request with the json output ...

2023-01-10 10:48 UTC, closed without merging