Hopefully fix issue #763
FOSSBilling/FOSSBilling pull request #769
Opened 2023-02-01 09:51 UTC by BelleNottelling

CGI shouldn't be included in that check, as it would make any server running CGI log the user in as the cron user.

I'm guessing this was done because CGI server's didn't show up as `cli` through `php_sapi_name()`, just in-case I added `http_response_code` as per the PHP docs:
"false will be returned if response_code is not provided and it is not invoked in a web server environment (such as from a CLI application)"

We can probably switch all checks for CLI to using that, but that requires more research

2023-02-01 09:52 UTC, jaapmarcus approved these changes

2023-02-01 10:42 UTC, jaapmarcus commented
Can confirm if the server is running is cgi mode or fcgi mode

2023-02-01 11:03 UTC, Jonpwatson5 requested changes
* @throws \Box_Exception If the script is running in CLI or CGI mode and there is no cron admin available.
 */
$di['loggedin_admin'] = function () use ($di) {
    if ('cli' === php_sapi_name() || str_starts_with(php_sapi_name(), 'cgi')) {
    if ('cli' === php_sapi_name() || !http_response_code()) {
        return $di['mod_service']('staff')->getCronAdmin();
    }
    }

2023-02-01 11:33 UTC, BelleNottelling commented
> * @throws \Box_Exception If the script is running in CLI or CGI mode and there is no cron admin available.
>       */
>       $di['loggedin_admin'] = function () use ($di) {
>       if ('cli' === php_sapi_name() || str_starts_with(php_sapi_name(), 'cgi')) {
>       if ('cli' === php_sapi_name() || !http_response_code()) {
>       return $di['mod_service']('staff')->getCronAdmin();
>       }
>       }

Why?...
This suggested change keeps the old if statement but then adds the new one inside of it, the old one is completely unnecessary & doesn't serve any point

2023-02-01 11:55 UTC, jaapmarcus commented
> * @throws \Box_Exception If the script is running in CLI or CGI mode and there is no cron admin available.
>   */
>   $di['loggedin_admin'] = function () use ($di) {
>   if ('cli' === php_sapi_name() || str_starts_with(php_sapi_name(), 'cgi')) {
>   if ('cli' === php_sapi_name() || !http_response_code()) {
>   return $di['mod_service']('staff')->getCronAdmin();
>   }
>   }

You should replace the code instead of adding  but as it works it should be fine...

2023-02-05 14:34 UTC, BelleNottelling commented
Unliked the issue that I don't expect to be resolved with this, especially since we have no confirmation that it works

2023-02-06 18:28 UTC, John-S4 approved these changes

2023-02-07 00:48 UTC, merged