Replace `admin_default` js autocomplete
FOSSBilling/FOSSBilling pull request #878
Opened 2023-03-01 09:42 UTC by shmshd

Replace `jquery-ui` autocomplete with `tom-select` selector.

2023-03-01 10:14 UTC, shmshd commented
![autocomplete](https://user-images.githubusercontent.com/11484121/222109930-1d22ef9e-d13c-438e-9d3e-3cbfb02f5e31.gif)

2023-03-01 10:22 UTC, evrifaessa commented
Thanks for the PR, it looks really nice. 🙂

But I feel like we first should discuss about importing Axios or not.

Some time ago, we've started migrating away from jQuery's AJAX to the native fetch() API.

Do we really need another dependency, Axios here?

2023-03-01 10:37 UTC, shmshd commented
> Some time ago, we've started migrating away from jQuery's AJAX to the native fetch() API.
> 
> Do we really need another dependency, Axios here?

The reason to choose `axios` is its browser support due to the `XMLHttpRequest` usage under the hood. The difference between both is almost 2% as per [caniuse.com](https://caniuse.com/).

2023-03-01 10:45 UTC, jaapmarcus commented
> Do we really need another dependency, Axios here?

Main difference is browsers older than 7 years. Should be care about it?
<img width="1537" alt="Screenshot 2023-03-01 at 11 44 03" src="https://user-images.githubusercontent.com/9754650/222117338-1e5c2d40-20cb-4a64-bc4c-96a26b2228f7.png">

2023-03-01 10:50 UTC, BelleNottelling commented
No, we shouldn't be worried about outdated web browsers. Maybe for the client area, but certainly not the admin panel

2023-03-01 10:58 UTC, evrifaessa commented
Old browsers shouldn't be much of a concern. I don't think it's enough of a reason to stop using the native fetch API in favor of Axios.

If it got merged, we would be using 3 different ways to do requests, AJAX, Fetch and Axios. Fetch by itself is pretty sufficient.

2023-03-01 11:07 UTC, John-S4 commented
Agree with all of the above, especially about not needing to support ancient browsers (including on the client area).

2023-03-01 13:51 UTC, jaapmarcus requested changes

2023-03-01 13:51 UTC, jaapmarcus commented on src/modules/Invoice/html_admin/mod_invoice_index.html.twig
> +    console.log();
Can be removed

2023-03-02 04:46 UTC, shmshd commented
Now client ID is shown in the selection result to easily identify the client from duplicate names.

![autocomplete-d](https://user-images.githubusercontent.com/11484121/222333330-b651fb90-692c-48dd-830f-9ba42cf0b007.gif)

2023-03-02 06:23 UTC, jaapmarcus commented
Can we also include the "Company" name?

2023-03-02 06:26 UTC, BelleNottelling commented
> Can we also include the "Company" name?

Not all of them will have that set

2023-03-02 06:27 UTC, shmshd commented
> Can we also include the "Company" name?

I did not want to change the API response. API provides only ID and Name.

2023-03-02 07:07 UTC, jaapmarcus commented
> > Can we also include the "Company" name?
> 
> Not all of them will have that set

I know but for example: User Y from  Company X calls and past worker who is in the contacts left few months ago I still need to search them them en the current method is going trough all the full list. 

If present we should include them in the api response and search functions

2023-03-02 07:35 UTC, BelleNottelling approved these changes

2023-03-02 09:08 UTC, evrifaessa approved these changes
Well done. Thanks for the PR 🙂

2023-03-02 09:21 UTC, jaapmarcus approved these changes

2023-03-02 09:22 UTC, merged